/**
 * Schedule A/B: logical field id → PDF template field name.
 * Single source for form-change resilience: when the template is revised,
 * re-inspect the PDF and update this map (and docs/form-requirements/schedule-ab.json).
 */
const FIELD_MAP: Record<string, string> = {
  // Header (court-ready)
  'header.debtor1_name': 'Debtor 1',
  'header.debtor2_name': 'Debtor 2',
  'header.district': 'Bankruptcy District Information',
  'header.case_number': 'Case number',
  // Part 1: Real property (template uses City, State, ZIP Code, County and type checkboxes for prop 1)
  'real_property.1.address': '1 1',
  'real_property.1.type': '1 1a',
  'real_property.1.city': 'City',
  'real_property.1.state': 'State',
  'real_property.1.zip': 'ZIP Code',
  'real_property.1.county': 'County',
  'real_property.1.value': 'undefined_2',
  'real_property.1.value_portion': 'undefined_3',
  'real_property.1.ownership_description': 'the entireties or a life estate if known',
  'real_property.1.type_singlefamily': 'Singlefamily home',
  'real_property.1.type_condo': 'Condominium or cooperative',
  'real_property.1.type_land': 'Land',
  'real_property.1.type_manufactured': 'Manufactured or mobile home',
  'real_property.1.type_timeshare': 'Timeshare',
  'real_property.1.type_other': 'Other',
  'real_property.1.type_duplex': 'Duplex or multiunit building',
  'real_property.1.type_investment': 'Investment property',
  'real_property.1.interest_debtor1_only': 'Who has interest in property',
  'real_property.1.interest_debtor2_only': 'Who has interest in property 2',
  'real_property.1.interest_joint': 'Who has interest in property 3',
  'real_property.1.interest_another': 'Who has interest in property 4',
  'real_property.2.address': '2_2',
  'real_property.2.city': 'City_2',
  'real_property.2.state': 'State_2',
  'real_property.2.zip': 'ZIP Code_2',
  'real_property.2.county': 'County_2',
  'real_property.2.county_alt': '2_3',
  'real_property.2.value': '2_4',
  // Part 2: Vehicles
  'vehicles.1.description': '3 1',
  'vehicles.1.mileage': '3 2',
  'vehicles.1.value': '3 4',
  'vehicles.2.description': '3_2',
  'vehicles.2.value': '3_3',
  // Part 4: Financial
  'financial.cash.amount': '16 Cash amount',
  'financial.cash.none': 'Check 16',
  'financial.accounts.none': 'Check 17',
  'financial.checking.1.account': '17.1 Checking account',
  'financial.checking.1.amount': '17.1 Checking amount',
  'financial.checking.2.account': '17.2 Checking account',
  'financial.checking.2.amount': '17.2 Checking amount',
  'financial.checking.3.account': '17.3 Checking account',
  'financial.checking.3.amount': '17.3 Checking amount',
  'financial.checking.4.account': '17.4 Checking account',
  'financial.checking.4.amount': '17.4 Checking amount',
  'financial.other.6.account': '17.6 Other financial account',
  'financial.other.6.amount': '17.6 Other financial amount',
  'financial.other.7.account': '17.7 Other financial account',
  'financial.other.7.amount': '17.7 Other financial amount',
  'financial.other.8.account': '17.8 Other financial account',
  'financial.other.8.amount': '17.8 Other financial amount',
  'financial.other.9.account': '17.9 Other financial account',
  'financial.other.9.amount': '17.9 Other financial amount',
  'financial.stocks_bonds.none': 'Check 18',
  'financial.non_public_stock.none': 'check 19',
  'financial.bonds.none': 'check 20',
  'financial.retirement.none': 'check 21',
  'financial.retirement.401k.desc': '21.1 401k or similar plan',
  'financial.retirement.401k.amount': '21.1 401k or similar plan amount',
  'financial.retirement.pension.desc': '21.2 Pension plan',
  'financial.retirement.pension.amount': '21.2 Pension plan amount',
  'financial.retirement.ira.desc': '21.3 IRA',
  'financial.retirement.ira.amount': '21.3 IRA amount',
  'financial.retirement.other.desc': '21.4 Retirement account',
  'financial.retirement.other.amount': '21.4 Retirement account amount',
  'financial.retirement.keogh.desc': '21.5 Keogh',
  'financial.retirement.keogh.amount': '21.5 Keogh amount',
  'financial.security_deposits.none': 'check 22',
  'financial.security_deposits.electric.desc': '22.1 Electric',
  'financial.security_deposits.electric.amount': '22.1 Electric amount',
  'financial.security_deposits.rental.desc': '22.4 Security deposit on rental unit',
  'financial.security_deposits.rental.amount': '22.4 Security deposit on rental unit amount',
  'financial.security_deposits.other.desc': '22.9 Other',
  'financial.security_deposits.other.amount': '22.9 Other amount',
  'financial.annuities.none': 'check 23',
  'financial.education_ira.none': 'check 24',
  'financial.trusts.none': 'check 25',
  'financial.patents.none': 'check 26',
  'financial.licenses.none': 'check 27',
  'financial.tax_refunds.none': 'check 28',
  'financial.tax_refunds.desc': '28 Tax refunds owed',
  'financial.tax_refunds.amount1': '28 Tax refunds owed amout1',
  'financial.tax_refunds.amount2': '28 Tax refunds owed amout2',
  'financial.tax_refunds.amount3': '28 Tax refunds owed amout3',
  'financial.family_support.none': 'check 29',
  'financial.other_amounts.none': 'check 30',
  'financial.other_assets.none': 'check 35',
  'financial.other_assets.text': '35',
  // Part 3: Household (lines 6–14)
  'household.6.description': '6 description',
  'household.6.amount': '6 description amount',
  'household.6.check': '6 check',
  'household.7.description': '7 description',
  'household.7.amount': '7 description amount',
  'household.7.check': '7 check',
  'household.8.description': '8 description',
  'household.8.amount': '8 description amount',
  'household.8.check': '8 check',
  'household.9.description': '9 description',
  'household.9.amount': '9 description amount',
  'household.9.check': '9 check',
  'household.10.description': '10 description',
  'household.10.amount': '10 description amount',
  'household.10.check': '10 check',
  'household.11.description': '11 description',
  'household.11.amount': '11 description amount',
  'household.11.check': '11 check',
  'household.12.description': '12 description',
  'household.12.amount': '12 description amount',
  'household.12.check': '12 check',
  'household.13.description': '13 description',
  'household.13.amount': '13 description amount',
  'household.13.check': 'check 13',
  'household.14.description': '14 description',
  'household.14.amount': '14 description amount',
  'household.14.check': 'check 14',
  // Part 5: Business
  'business.none.37': 'check 37',
  'business.none.38': 'check 38',
  'business.none.39': 'check 39',
  'business.none.40': 'check 40',
  'business.none.41': 'check 41',
  'business.none.42': 'check 42',
  'business.details': '38 Accounts receivable or commissions already earned',
  // Part 6: Farm
  'farm.none.46': 'check 46',
  'farm.none.47': 'check 47',
  'farm.none.48': 'check 48',
  'farm.none.49': 'check 49',
  'farm.none.50': 'check 50',
  'farm.none.51': 'check 51',
  'farm.details': '47 Farm Animals',
  // Part 8: Totals – do NOT use undefined_155 (Part 7 Other) or undefined_163 (Part 5 Line 59).
  // Map only when manifest identifies correct total fields (see docs/form-fields/form_b106ab-manifest.json).
  // 'total.real_estate': TBD,
  // 'total.personal_property': TBD,
};

export function getScheduleABPdfFieldName(logicalId: string): string | undefined {
  return FIELD_MAP[logicalId];
}

/** Resolve PDF field name; fallback to logicalId if not in map (for backward compat or dynamic keys). */
export function resolveScheduleABField(logicalId: string): string {
  return getScheduleABPdfFieldName(logicalId) ?? logicalId;
}
